### ISSUE TITLE
The value specified for "RequestRelation" is incorrect.

### ISSUE THREAD

**Issue by csKyou** [personium/wakaba-business-app#4]
Please specify the application cell instead of the my cell URL.
The application cell must be set for each target information.

**Comment by dixonsiu** [comment]
In order to allow other developer to fix it promptly, please provide details on how to fix the issue. For example,  
1. which file to fix
sendMessage.js
1. current source codes

        cellUrl = Common.cellUrl;
        messageBody.RequestRelation = cellUrl + "__relation/__/" + name;

1. suggested source codes
cellURL must be the target's cell URL.
    1. Calorie Smile (https://demo.personium.io/hn-app-genki/)
    1. LifeBeat (https://demo.personium.io/hn-app-neurosky/)
